export const TYPES = {
  INIT_PRODUCTS: "INIT_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  TOTAL_AMOUNT: "TOTAL_AMOUNT",
  CHANGE_PRICE_TO_ARS: "CHANGE_PRICE_TO_ARS",
  CHANGE_PRICE_TO_EUR: "CHANGE_PRICE_TO_EUR",
  CHANGE_PRICE_TO_USD: "CHANGE_PRICE_TO_USD",
};
